---
title: "Dating Conflict Analysis"
author: "Kate Mills"
date: "November 10, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = FALSE,
	message = FALSE,
	warning = FALSE
)
```

Load required packages and scripts (no input needed)
```{r setup, include=FALSE}
knitr::opts_chunk$set(
	message = FALSE,
	warning = FALSE,
	include = FALSE
)
packages <- c( "tidyverse", "RODBC", "data.table",
               "ggplot2","lavaan","semPlot")
if (length(setdiff(packages, rownames(installed.packages()))) > 0) {
  install.packages(setdiff(packages, rownames(installed.packages())))
}
lapply(packages, library, character.only = TRUE)
workdir=substring(paste0(getwd()),0,53)

resave_graphs=FALSE

# Kate's custom theme
theme_kate <- function () { 
    theme_bw() +
  theme_minimal(base_size = 14, base_family = "Avenir") +
  theme(axis.line = element_line(colour = "black"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.border = element_blank(),
        panel.background = element_blank(),
        legend.position="none")
}
```

Load data
```{r, message=FALSE, warning=FALSE, include=FALSE}
conn <- RODBC::odbcConnect(dsn="PInf1")
participants <- data.table(RODBC::sqlQuery(conn,"SELECT * From PInf1.dbo.SMaster")) %>%
  select(SID,Gender,Latino,EthWhite,EthBlack,EthAsian,EthNAm,EthPacIs,EthOther)
surveydata <- data.table(RODBC::sqlQuery(conn,"SELECT * From PInf1.dbo.SWave"))
rm(conn)

EMA_waves3456<-read.csv("../../EMA_Wave3456.csv",header=TRUE,stringsAsFactors = FALSE)
```

Clean data
```{r, message=FALSE, warning=FALSE, include=FALSE}
# Clean up ethnicity data
demographics <- participants %>%
  mutate(Ethnicity=ifelse(rowSums(select(., contains("Eth")),na.rm = TRUE)>1,"Multiethnic",
                          ifelse(rowSums(select(., contains("Eth")),na.rm = TRUE)<1,NA,
                          1))) %>%
  mutate(Ethnicity=ifelse(!Ethnicity=="Multiethnic" & EthWhite==1,"White",
                          ifelse(!Ethnicity=="Multiethnic" & EthOther==1,"Other",
                                 ifelse(!Ethnicity=="Multiethnic" & EthBlack==1,"AfricanAmerican",
                                 ifelse(!Ethnicity=="Multiethnic" & EthAsian==1,"AsianAmerican",
                                        ifelse(!Ethnicity=="Multiethnic" & EthNAm==1,"NativeAmerican",
                                               ifelse(!Ethnicity=="Multiethnic" & EthPacIs==1,"PacificIslander",
                                                      Ethnicity))))))) %>%
  select(SID,Gender,Ethnicity,Latino)

# Clean up puberty data
puberty<-left_join(demographics,(surveydata %>%
                                   select(SID,WID,contains("Pub")))) %>%
  mutate(PubSpurt=PubSpurt+1,
         PubHair=PubHair+1,
         PubZits=PubZits+1,
         PubVoice=PubVoice+1,
         PubFace=PubFace+1,
         PubBreast=PubBreast+1,
         MensesStarted=ifelse(PubMenses==0,1,
                              ifelse(PubMenses>0,4,NA))) %>%
  mutate(PDS_Female=ifelse(Gender==0,rowMeans(cbind(PubSpurt,PubHair,PubZits,PubBreast,MensesStarted),na.rm = FALSE),NA),
         PDS_Male=ifelse(Gender==1,rowMeans(cbind(PubSpurt,PubHair,PubZits,PubVoice,PubFace),na.rm = FALSE),NA),
         Puberty_Category=ifelse(Gender==0,
                                 ifelse(rowSums(cbind(PubHair,PubBreast),
                                                na.rm=TRUE)==2 & MensesStarted==1,"Prepubertal",
                                 ifelse(rowSums(cbind(PubHair,PubBreast),
                                                na.rm=TRUE)==3 & MensesStarted==1,"Early Pubertal",
                                 ifelse(rowSums(cbind(PubHair,PubBreast),
                                                na.rm=TRUE)>3 & MensesStarted==1,"Midpubertal",
                                 ifelse(rowSums(cbind(PubHair,PubBreast)
                                                ,na.rm=TRUE)<= 7 & MensesStarted==4,"Late pubertal",
                                 ifelse(rowSums(cbind(PubHair,PubBreast),
                                                na.rm=TRUE)==8 & MensesStarted==4,"Postpubertal",NA))))),
                            ifelse(Gender==1,
                                 ifelse(rowSums(cbind(PubHair,PubVoice,PubFace),
                                                na.rm=TRUE)==3,"Prepubertal",
                                 ifelse(rowSums(cbind(PubHair,PubVoice,PubFace),
                                                na.rm=TRUE)>3 &
                                          rowSums(cbind(PubHair,PubVoice,PubFace),
                                                  na.rm=TRUE)<6,"Early Pubertal",
                                 ifelse(rowSums(cbind(PubHair,PubVoice,PubFace),
                                                na.rm=TRUE)>5&
                                          rowSums(cbind(PubHair,PubVoice,PubFace),
                                                  na.rm=TRUE)<9,"Midpubertal",
                                 ifelse(rowSums(cbind(PubHair,PubVoice,PubFace),
                                                na.rm=TRUE)>8&
                                          rowSums(cbind(PubHair,PubVoice,PubFace),
                                                  na.rm=TRUE)<12,"Late pubertal",
                                        ifelse(rowSums(cbind(PubHair,PubVoice,PubFace),
                                                       na.rm=TRUE)==12,"Postpubertal",NA))))),NA)),
         PeriodStartAge=ifelse(PubMenses==0,0,
                            ifelse(!PubMenses==0,PubMenses+5,NA))) %>%
  select(-PubSpurt,-PubZits,-PubHair,-PubBreast,-PubVoice,-PubFace,-PubMenses,-PubKiss) %>%
  mutate(Puberty_Category=factor(Puberty_Category,levels = c("Prepubertal", "Early Pubertal", "Midpubertal",
                                                             "Late pubertal","Postpubertal"))) %>%
  mutate(Puberty_3group=ifelse(Gender==0,
                               ifelse(PDS_Female<=3,"less",
                                      ifelse(PDS_Female>3 & PDS_Female<3.8,"avg",
                                             ifelse(PDS_Female>=3.8,"more",NA))),
                               ifelse(Gender==1,
                                      ifelse(PDS_Male<=2.4,"less",
                                             ifelse(PDS_Male>2.4 & PDS_Male<3.2,"avg",
                                                    ifelse( PDS_Male>=3.2,"more",NA))),NA)))

# Calculate the mean and total opportunities monitoring scores
opportunities<-surveydata %>% 
  select(SID,WID,Kiss3Mo,Laid3Mo,PartyNA3Mo) %>%
  mutate(OppMonitorMean=round(rowMeans(cbind(Kiss3Mo,Laid3Mo,PartyNA3Mo),na.rm=FALSE),2),
         OppMonitorTotal=rowSums(cbind(Kiss3Mo,Laid3Mo,PartyNA3Mo),na.rm=TRUE)) %>%
  filter(!is.na(OppMonitorMean))

# Clean oldest partner age to identify the oldest partner by grade 9 (Wave 5)
age_oldest_partner<-surveydata %>% 
  select(SID,WID,AgeOldBFGF2) %>%
  filter(!is.na(AgeOldBFGF2),
         WID==5) %>%
  group_by(SID) %>%
  do({oldest_age<-(sort(.$AgeOldBFGF2,decreasing = TRUE)[[1]])
      dplyr::mutate(.,oldest=oldest_age)
  })

# Calculate the mean and total dating conflict score
dating_conflict<-surveydata %>% 
  select(SID,WID,Jealous,IValued,IDone,MeAngry,MeanTone,PutDown,KepTrak,BlaMe,
         AcFlirt,Fright,MadeFun,TTHurt,TTEnd,TTHit) %>%
  mutate(DatingConflictMean=round(rowMeans(cbind(Jealous,IValued,IDone,MeAngry,MeanTone,PutDown,KepTrak,BlaMe,
         AcFlirt,Fright,MadeFun,TTHurt,TTEnd,TTHit),na.rm=FALSE),2),
         DatingConflictTotal=rowSums(cbind(Jealous,IValued,IDone,MeAngry,MeanTone,PutDown,KepTrak,BlaMe,
         AcFlirt,Fright,MadeFun,TTHurt,TTEnd,TTHit),na.rm=TRUE)) %>%
  mutate(threatening_mean=round(rowMeans(cbind(IValued,Fright,TTHurt,TTHit),na.rm=FALSE),2),
         threatening_total=round(rowSums(cbind(IValued,Fright,TTHurt,TTHit),na.rm=TRUE),2),
         verbal_mean=round(rowMeans(cbind(Jealous,IDone,MeAngry,MeanTone,PutDown,KepTrak,BlaMe,
         AcFlirt,MadeFun,TTEnd),na.rm=FALSE),2),
         verbal_total=round(rowSums(cbind(Jealous,IDone,MeAngry,MeanTone,PutDown,KepTrak,BlaMe,
         AcFlirt,MadeFun,TTEnd),na.rm=TRUE),2)) %>%
  filter(!is.na(DatingConflictMean))

# Process the EMA data
EMA_data<-EMA_waves3456 %>%
  mutate(SID=sid) %>%
  select(SID, complete, WID,WithBFGF,AdultPresent,NumAdults,Whereareyou) %>%
  filter(!is.na(WithBFGF),!is.na(AdultPresent)) %>%
  mutate(Location=ifelse(Whereareyou==1,"home",
                  ifelse(Whereareyou==2,"someones_house",
                  ifelse(Whereareyou==3,"school",
                  ifelse(Whereareyou==4,"going_somewhere",
                  ifelse(Whereareyou==5,"out_and_about",NA))))),
         WithBFGF=ifelse(WithBFGF==1,"Yes",
                         ifelse(WithBFGF==0,"No",NA)),
         AdultPresent=ifelse(AdultPresent==1,"Yes",
                         ifelse(AdultPresent==0,"No",NA))) %>%
  select(-Whereareyou) 

NumCompleteEMA<- EMA_data %>%
  group_by(SID,WID,complete) %>%
  summarize(totalEMA=n()) %>%
  ungroup()

EMA_count <- left_join((EMA_data %>%
  group_by(SID,WID,WithBFGF,AdultPresent) %>%
  summarize(count=n()) %>%
  ungroup()),
  (NumCompleteEMA %>%
     select(SID,WID,totalEMA)),
  by=c("SID","WID")) %>%
  mutate(ratio=round(count/totalEMA,3))

# Calculate willingness and intentions to have risky sex
willint_risky_sex<-surveydata %>% 
  select(SID,WID,HaveGfBf,PullOut,HaveSElse,AptOralSex,AptSex,AptSexCondom,PlanUnproSex,YrUnproSex) %>%
  mutate(WillingRiskySexMean=round(rowMeans(cbind(HaveGfBf,PullOut,HaveSElse,AptOralSex,AptSex,AptSexCondom),na.rm=FALSE),2),
         WillingRiskySexTotal=rowSums(cbind(HaveGfBf,PullOut,HaveSElse,AptOralSex,AptSex,AptSexCondom),na.rm=TRUE),
         IntentionRiskSexMean=round(rowMeans(cbind(PlanUnproSex,YrUnproSex),na.rm=FALSE),2),
         IntentionRiskSexTotal=rowSums(cbind(PlanUnproSex,YrUnproSex),na.rm=TRUE)) %>%
  filter(!is.na(IntentionRiskSexMean & WillingRiskySexMean))


```

Descriptives of raw data
```{r, echo=FALSE, message=FALSE, warning=FALSE}

# Set labels
wave_labels<-c("1"="8th Grade","5"="9th Grade","9"="10th Grade","11"="11th grade")
gender_labels<-c("0" = "Female", "1" = "Male")
latino_labels<-c("0" = "Not Latino", "1" = "Latino")

# Puberty Distribution
## Females
Female_Puberty<-ggplot(puberty, aes(x=PDS_Female,
                    colour=as.factor(WID)))+
               geom_density(alpha=.7,
                            size=1.5) +
  labs(x="Pubertal Measure",colour='Wave') +
  ggtitle("Puberty Distribution (Female)") +
  theme_kate()
Female_Puberty
if(resave_graphs){ggsave(plot = Female_Puberty,file=paste(workdir,"graphs/Female_PubertybyWave_dist.png",sep = ""),
        width = 6, height = 4, dpi = 300,units="in")}

## Males
Male_Puberty<-ggplot(puberty, aes(x=PDS_Male,
                    colour=as.factor(WID)))+
               geom_density(alpha=.7,
                            size=1.5) +
  labs(x="Pubertal Measure",colour='Wave') +
  ggtitle("Puberty Distribution (Male)") +
  theme_kate()
Male_Puberty
if(resave_graphs){ggsave(plot = Male_Puberty,file=paste(workdir,"graphs/Male_PubertybyWave_dist.png",sep = ""),
       width = 6, height = 4, dpi = 300,units="in")}

# Check distribution of Puberty Categories
puberty_dist_grade<-puberty %>%
  filter(!is.na(Puberty_Category)) %>%
  group_by(Puberty_Category,Gender,WID) %>%
  summarize(count=n())

# Plot distribution of Puberty Categories
Puberty_Categories<-ggplot(puberty_dist_grade, aes(x=WID,y=count,
                    colour=Puberty_Category)) +
  geom_line(aes(group=Puberty_Category), size=1)+
  facet_grid(.~Gender,
             scales='free',
             labeller=as_labeller(gender_labels))+
  labs(x="Wave",colour="Puberty Category") +
  ggtitle("Puberty Category Distribution") +
  theme_kate()+theme(legend.position="bottom")
Puberty_Categories
if(resave_graphs){ggsave(plot = Puberty_Categories,file=paste(workdir,"graphs/Puberty_Categories_GroupedbyWave.png",sep = ""),
       width = 6, height = 4, dpi = 300,units="in")}

Puberty_Categories<-ggplot(puberty_dist_grade, aes(x=as.factor(Gender), y=count, fill=Puberty_Category)) +
    geom_bar(colour="black", stat="identity") +
  facet_grid(.~WID,
             scales='free',
              labeller=as_labeller(wave_labels))+
  labs(x="Gender",fill="Puberty Category") +
  ggtitle("Puberty Category Distribution") +
  scale_x_discrete(labels=c("0" = "Female", "1" = "Male"))+
  theme_kate()
Puberty_Categories
if(resave_graphs){ggsave(plot = Puberty_Categories,file=paste(workdir,"graphs/Puberty_Categories_GroupedbyGender.png",sep = ""),
       width = 8, height = 6, dpi = 150,units="in")}


# Opportunities Monitoring
opp_montioring_dist_mean<-ggplot(opportunities, aes(x=OppMonitorMean,
                    colour=as.factor(WID)))+
               geom_density(alpha=.7,
                            size=1.5) +
  labs(x="Opportunities Monitoring",colour='Wave') +
  ggtitle("Opportunities Monitoring (mean) Distribution by Wave") +
  theme_kate()

opp_montioring_dist_mean

if(resave_graphs){ggsave(plot = opp_montioring_dist_mean,file=paste(workdir,"graphs/opp_montioring_dist_mean.png",sep = ""),
       width = 6, height = 4, dpi = 300,units="in")}

opp_montioring_dist_total<-ggplot(opportunities, aes(x=OppMonitorTotal,
                    colour=as.factor(WID)))+
               geom_density(alpha=.7,
                            size=1.5) +
  labs(x="Opportunities Monitoring",colour='Wave') +
  ggtitle("Opportunities Monitoring (total) Distribution by Wave") +
  theme_kate()

opp_montioring_dist_total
if(resave_graphs){ggsave(plot = opp_montioring_dist_total,file=paste(workdir,"graphs/opp_montioring_dist_total.png",sep = ""),
       width = 6, height = 4, dpi = 300,units="in")}

# Dating Conflict
## Item level
dating_conflict_des_item<-gather(dating_conflict[1:16],"item","value",3:16) %>%
  group_by(WID,item) %>%
  summarize(mean=round(mean(value),3),
            count=sum(value>0)) %>%
  ungroup()

dating_conflict_item_count<-ggplot(dating_conflict_des_item, aes(x=WID,y=count,
                    colour=item)) +
  geom_line(aes(group=item), size=1)+
  labs(x="Wave",colour="CADRI Item") +
  ggtitle("CADRI Item Count") +
  theme_kate()+theme(legend.position="bottom")
dating_conflict_item_count
if(resave_graphs){ggsave(plot = dating_conflict_item_count,
                         file=paste(workdir,"graphs/dating_conflict_item_count.png",sep = ""),
                         width = 6, height = 4, dpi = 300,units="in")}

dating_conflict_item_mean<-ggplot(dating_conflict_des_item, aes(x=WID,y=mean,
                    colour=item)) +
  geom_line(aes(group=item), size=1)+
  labs(x="Wave",colour="CADRI Item") +
  ggtitle("CADRI Item mean") +
  theme_kate()+theme(legend.position="bottom")
dating_conflict_item_mean
if(resave_graphs){ggsave(plot = dating_conflict_item_mean,
                         file=paste(workdir,"graphs/dating_conflict_item_mean.png",sep = ""),
                         width = 6, height = 4, dpi = 300,units="in")}

## Subscale level
dating_conflict_subscale<-dating_conflict %>%
  mutate(threatening_mean=round(rowMeans(cbind(IValued,Fright,TTHurt,TTHit),na.rm=FALSE),2),
         threatening_total=round(rowSums(cbind(IValued,Fright,TTHurt,TTHit),na.rm=TRUE),2),
         verbal_mean=round(rowMeans(cbind(Jealous,IDone,MeAngry,MeanTone,PutDown,KepTrak,BlaMe,
         AcFlirt,MadeFun,TTEnd),na.rm=FALSE),2),
         verbal_total=round(rowSums(cbind(Jealous,IDone,MeAngry,MeanTone,PutDown,KepTrak,BlaMe,
         AcFlirt,MadeFun,TTEnd),na.rm=TRUE),2))%>%
  select(WID,SID,contains("_mean"),contains("_total")) %>%
  gather("subscale","value",3:6) 

dating_conflict_sum_subscale<-dating_conflict_subscale%>%
  group_by(WID,subscale) %>%
  summarize(mean=round(mean(value),3),
            min=round(min(value),3),
            max=round(max(value),3),
            sd=round(sd(value),3)) %>% 
  ungroup()

dating_conflict_subscale_mean_wave11<-ggplot(data=dating_conflict_subscale %>%
                                        filter(grepl("mean",subscale)) %>%
                                        filter(!is.na(value)) %>%
                                        filter(WID==11),
                                      aes(x=value)) + 
  geom_histogram(breaks=seq(0, 3, by=.2), 
                 colour="dodgerblue", 
                 fill="dodgerblue", 
                 alpha = .2)+
     facet_grid(.~subscale,
             scales='free') +
  ggtitle("CADRI Subscale (Mean) Distribution Wave 11") +
  theme_kate()+theme(legend.position="bottom")
dating_conflict_subscale_mean_wave11
if(resave_graphs){ggsave(plot = dating_conflict_subscale_mean_wave11,
                         file=paste(workdir,"graphs/CADRI_Subscales_Wave11.png",sep = ""),
       width = 6, height = 4, dpi = 300,units="in")}

dating_conflict_subscale_mean<-ggplot(dating_conflict_sum_subscale%>%
                                        filter(grepl("mean",subscale)),
                  aes(x=as.factor(WID),y=mean,colour=subscale)) +
  geom_point(position=position_dodge(.1),aes(colour=subscale), size=2) +
  geom_errorbar(position=position_dodge(.1), 
                aes(ymax=mean + sd, ymin=mean - sd,colour=subscale),
                width=0.5) +
  labs(x='Wave', y='CADRI subscale mean') +
  theme_kate()+theme(legend.position="bottom")
dating_conflict_subscale_mean
if(resave_graphs){ggsave(plot = dating_conflict_subscale_mean,
                         file=paste(workdir,"graphs/CADRI_Subscales_MeanbyWave.png",sep = ""),
       width = 6, height = 4, dpi = 300,units="in")}



dating_conflict_subscale_total<-ggplot(dating_conflict_sum_subscale%>%
                                        filter(grepl("total",subscale)),
                  aes(x=as.factor(WID),y=mean,colour=subscale)) +
  geom_point(position=position_dodge(.1),aes(colour=subscale), size=2) +
  geom_errorbar(position=position_dodge(.1), 
                aes(ymax=mean + sd, ymin=mean - sd,colour=subscale),
                width=0.5) +
  labs(x='Wave', y='CADRI subscale total') +
  theme_kate()+theme(legend.position="bottom")
dating_conflict_subscale_total
if(resave_graphs){ggsave(plot = dating_conflict_subscale_total,
                         file=paste(workdir,"graphs/CADRI_Subscales_TotalbyWave.png",sep = ""),
       width = 6, height = 4, dpi = 300,units="in")}


## Overall
dating_conflict_dist_mean<-ggplot(dating_conflict, aes(x=DatingConflictMean,
                    colour=as.factor(WID)))+
               geom_density(alpha=.7,
                            size=1.5) +
  labs(x="Dating Conflict",colour='Wave') +
  ggtitle("Dating Conflict (mean) Distribution by Wave") +
  theme_kate()
dating_conflict_dist_mean
if(resave_graphs){ggsave(plot = dating_conflict_dist_mean,file=paste(workdir,"graphs/dating_conflict_dist_mean.png",sep = ""),
       width = 6, height = 4, dpi = 300,units="in")}

dating_conflict_dist_total<-ggplot(dating_conflict, aes(x=DatingConflictTotal,
                    colour=as.factor(WID)))+
               geom_density(alpha=.7,
                            size=1.5) +
  labs(x="Dating Conflict",colour='Wave') +
  ggtitle("Dating Conflict (total) Distribution by Wave") +
  theme_kate()+theme(legend.position="bottom")
dating_conflict_dist_total

if(resave_graphs){ggsave(plot = dating_conflict_dist_total,file=paste(workdir,"graphs/dating_conflict_dist_total.png",sep = ""),
       width = 6, height = 4, dpi = 300,units="in")}

# Oldest Partner reported by Wave
age_oldest_partner_allwaves<-surveydata %>% 
  select(SID,WID,AgeOldBFGF2) %>%
  filter(!is.na(AgeOldBFGF2)) %>%
  group_by(SID) %>%
  do({oldest_age<-(sort(.$AgeOldBFGF2,decreasing = TRUE)[[1]])
      dplyr::mutate(.,oldest=oldest_age)
  })
age_partner_dist<-ggplot(left_join(age_oldest_partner_allwaves,
                                   (demographics %>% select(SID,Gender)),
                                   by="SID") %>% filter(!is.na(Gender)),
                         aes(x=AgeOldBFGF2,
                    colour=as.factor(WID)))+
               geom_density(alpha=.7,
                            size=1.5) +
  facet_grid(.~as.factor(Gender),
             scales='free',
             labeller=as_labeller(gender_labels))+
  labs(x="Age Oldest Partner",colour='Wave') +
  ggtitle("Age Oldest Partner Distribution by Wave") +
  theme_kate()
age_partner_dist
if(resave_graphs){ggsave(plot = age_partner_dist,
       file=paste(workdir,"graphs/age_partner_dist.png",sep = ""),
       width = 6, height = 4, dpi = 300,units="in")}
```

Create dataset that has all IVs and DVs in conceptual model
```{R}
thedata1<-left_join((EMA_count %>%
                      filter(WithBFGF=="Yes" & AdultPresent=="No") %>%
                      select(SID,WID,ratio) %>%
                      group_by(SID) %>%
                      summarize(EMAaloneBFGF=round(mean(ratio),3))%>%
                      ungroup()),
                   (puberty %>%
                      filter(WID==c(1)) %>%
                      mutate(Puberty_2group=ifelse(Puberty_3group=="more","avg",Puberty_3group)) %>%
                      select(SID,Gender,Latino,Puberty_3group,Puberty_2group)),
                    by = c("SID")) 

subs_noBFGFalone<-unique(EMA_count %>% 
  filter(!SID %in% thedata1$SID) %>%
    select(SID))

thedata<-bind_rows(thedata1,
                   (puberty %>%
                      filter(WID==c(1)) %>%
                      mutate(Puberty_2group=ifelse(Puberty_3group=="more","avg",Puberty_3group)) %>%
                      select(SID,Gender,Latino,Puberty_3group,Puberty_2group) %>%
                      filter(SID %in% subs_noBFGFalone$SID) %>%
                      mutate(EMAaloneBFGF=0))) %>%
  mutate(Gender=ifelse(Gender==0,"Female",
                       ifelse(Gender==1,"Male",NA))) %>%
  mutate(Gender=as.factor(Gender),
         Puberty_3group=factor(Puberty_3group,levels=c("less","avg","more")),
         Puberty_2group=factor(Puberty_2group,levels=c("less","avg")),
         Ethnicity=as.factor(Latino))


thedata<-full_join(thedata,(dating_conflict %>%
                      filter(WID==c(9)) %>%
                      select(SID,DatingConflictMean,threatening_mean,verbal_mean)))

thedata<-full_join(thedata,(opportunities %>%
                      filter(WID==c(5)) %>%
                      select(SID,OppMonitorMean)),by=c("SID"))

thedata<-full_join(thedata,(age_oldest_partner %>%
                      filter(WID==c(5)) %>%
                      select(SID,oldest)),by=c("SID"))

thedata<-full_join(thedata,(willint_risky_sex %>%
                              filter(WID==c(9)) %>%
                              select(SID,WillingRiskySexMean,IntentionRiskSexTotal)))

thedata<-thedata[c("SID","Gender","Ethnicity","Puberty_3group","Puberty_2group","OppMonitorMean","oldest","EMAaloneBFGF",
                "DatingConflictMean","threatening_mean","verbal_mean","WillingRiskySexMean","IntentionRiskSexTotal")] %>%
  filter(!is.na(Gender)) 

thedata_female<-filter(thedata, Gender=="Female")
thedata_male<-filter(thedata, Gender=="Male")

# Print stats for descriptives table #

## Opportunities Monitoring
print(paste(length(na.omit(thedata$OppMonitorMean)),round(mean(thedata$OppMonitorMean,na.rm=TRUE),2),
             round(sd(thedata$OppMonitorMean,na.rm=TRUE),3),round(median(thedata$OppMonitorMean,na.rm=TRUE),2),
             round(min(thedata$OppMonitorMean,na.rm=TRUE),2),round(max(thedata$OppMonitorMean,na.rm=TRUE),2),sep = ","))
### Females
print(paste(length(na.omit(thedata_female$OppMonitorMean)),round(mean(thedata_female$OppMonitorMean,na.rm=TRUE),2),
             round(sd(thedata_female$OppMonitorMean,na.rm=TRUE),3),round(median(thedata_female$OppMonitorMean,na.rm=TRUE),2),
             round(min(thedata_female$OppMonitorMean,na.rm=TRUE),2),round(max(thedata_female$OppMonitorMean,na.rm=TRUE),2),sep = ","))

### Males
print(paste(length(na.omit(thedata_male$OppMonitorMean)),round(mean(thedata_male$OppMonitorMean,na.rm=TRUE),2),
             round(sd(thedata_male$OppMonitorMean,na.rm=TRUE),3),round(median(thedata_male$OppMonitorMean,na.rm=TRUE),2),
             round(min(thedata_male$OppMonitorMean,na.rm=TRUE),2),round(max(thedata_male$OppMonitorMean,na.rm=TRUE),2),sep = ","))

## EMA
print(paste(length(na.omit(thedata$EMAaloneBFGF)),round(mean(thedata$EMAaloneBFGF,na.rm=TRUE),2),
             round(sd(thedata$EMAaloneBFGF,na.rm=TRUE),3),round(median(thedata$EMAaloneBFGF,na.rm=TRUE),2),
             round(min(thedata$EMAaloneBFGF,na.rm=TRUE),2),round(max(thedata$EMAaloneBFGF,na.rm=TRUE),2),sep = ","))
### Females
print(paste(length(na.omit(thedata_female$EMAaloneBFGF)),round(mean(thedata_female$EMAaloneBFGF,na.rm=TRUE),2),
             round(sd(thedata_female$EMAaloneBFGF,na.rm=TRUE),3),round(median(thedata_female$EMAaloneBFGF,na.rm=TRUE),2),
             round(min(thedata_female$EMAaloneBFGF,na.rm=TRUE),2),round(max(thedata_female$EMAaloneBFGF,na.rm=TRUE),2),sep = ","))

### Males
print(paste(length(na.omit(thedata_male$EMAaloneBFGF)),round(mean(thedata_male$EMAaloneBFGF,na.rm=TRUE),2),
             round(sd(thedata_male$EMAaloneBFGF,na.rm=TRUE),3),round(median(thedata_male$EMAaloneBFGF,na.rm=TRUE),2),
             round(min(thedata_male$EMAaloneBFGF,na.rm=TRUE),2),round(max(thedata_male$EMAaloneBFGF,na.rm=TRUE),2),sep = ","))

## Dating Conflict
print(paste(length(na.omit(thedata$DatingConflictMean)),round(mean(thedata$DatingConflictMean,na.rm=TRUE),2),
             round(sd(thedata$DatingConflictMean,na.rm=TRUE),3),round(median(thedata$DatingConflictMean,na.rm=TRUE),2),
             round(min(thedata$DatingConflictMean,na.rm=TRUE),2),round(max(thedata$DatingConflictMean,na.rm=TRUE),2),sep = ","))
### Females
print(paste(length(na.omit(thedata_female$DatingConflictMean)),round(mean(thedata_female$DatingConflictMean,na.rm=TRUE),2),
             round(sd(thedata_female$DatingConflictMean,na.rm=TRUE),3),round(median(thedata_female$DatingConflictMean,na.rm=TRUE),2),
             round(min(thedata_female$DatingConflictMean,na.rm=TRUE),2),round(max(thedata_female$DatingConflictMean,na.rm=TRUE),2),sep = ","))

### Males
print(paste(length(na.omit(thedata_male$DatingConflictMean)),round(mean(thedata_male$DatingConflictMean,na.rm=TRUE),2),
             round(sd(thedata_male$DatingConflictMean,na.rm=TRUE),3),round(median(thedata_male$DatingConflictMean,na.rm=TRUE),2),
             round(min(thedata_male$DatingConflictMean,na.rm=TRUE),2),round(max(thedata_male$DatingConflictMean,na.rm=TRUE),2),sep = ","))

## Dating Conflict Threat subscale
print(paste(length(na.omit(thedata$threatening_mean)),round(mean(thedata$threatening_mean,na.rm=TRUE),2),
             round(sd(thedata$threatening_mean,na.rm=TRUE),3),round(median(thedata$threatening_mean,na.rm=TRUE),2),
             round(min(thedata$threatening_mean,na.rm=TRUE),2),round(max(thedata$threatening_mean,na.rm=TRUE),2),sep = ","))
### Females
print(paste(length(na.omit(thedata_female$threatening_mean)),round(mean(thedata_female$threatening_mean,na.rm=TRUE),2),
             round(sd(thedata_female$threatening_mean,na.rm=TRUE),3),round(median(thedata_female$threatening_mean,na.rm=TRUE),2),
             round(min(thedata_female$threatening_mean,na.rm=TRUE),2),round(max(thedata_female$threatening_mean,na.rm=TRUE),2),sep = ","))

### Males
print(paste(length(na.omit(thedata_male$threatening_mean)),round(mean(thedata_male$threatening_mean,na.rm=TRUE),2),
             round(sd(thedata_male$threatening_mean,na.rm=TRUE),3),round(median(thedata_male$threatening_mean,na.rm=TRUE),2),
             round(min(thedata_male$threatening_mean,na.rm=TRUE),2),round(max(thedata_male$threatening_mean,na.rm=TRUE),2),sep = ","))


## Dating Conflict Verbal subscale
print(paste(length(na.omit(thedata$verbal_mean)),round(mean(thedata$verbal_mean,na.rm=TRUE),2),
             round(sd(thedata$verbal_mean,na.rm=TRUE),3),round(median(thedata$verbal_mean,na.rm=TRUE),2),
             round(min(thedata$verbal_mean,na.rm=TRUE),2),round(max(thedata$verbal_mean,na.rm=TRUE),2),sep = ","))
### Females
print(paste(length(na.omit(thedata_female$verbal_mean)),round(mean(thedata_female$verbal_mean,na.rm=TRUE),2),
             round(sd(thedata_female$verbal_mean,na.rm=TRUE),3),round(median(thedata_female$verbal_mean,na.rm=TRUE),2),
             round(min(thedata_female$verbal_mean,na.rm=TRUE),2),round(max(thedata_female$verbal_mean,na.rm=TRUE),2),sep = ","))

### Males
print(paste(length(na.omit(thedata_male$verbal_mean)),round(mean(thedata_male$verbal_mean,na.rm=TRUE),2),
             round(sd(thedata_male$verbal_mean,na.rm=TRUE),3),round(median(thedata_male$verbal_mean,na.rm=TRUE),2),
             round(min(thedata_male$verbal_mean,na.rm=TRUE),2),round(max(thedata_male$verbal_mean,na.rm=TRUE),2),sep = ","))


## Willingness to engage in risky sex
print(paste(length(na.omit(thedata$WillingRiskySexMean)),round(mean(thedata$WillingRiskySexMean,na.rm=TRUE),2),
             round(sd(thedata$WillingRiskySexMean,na.rm=TRUE),3),round(median(thedata$WillingRiskySexMean,na.rm=TRUE),2),
             round(min(thedata$WillingRiskySexMean,na.rm=TRUE),2),round(max(thedata$WillingRiskySexMean,na.rm=TRUE),2),sep = ","))

### Females
print(paste(length(na.omit(thedata_female$WillingRiskySexMean)),round(mean(thedata_female$WillingRiskySexMean,na.rm=TRUE),2),
             round(sd(thedata_female$WillingRiskySexMean,na.rm=TRUE),3),round(median(thedata_female$WillingRiskySexMean,na.rm=TRUE),2),
             round(min(thedata_female$WillingRiskySexMean,na.rm=TRUE),2),round(max(thedata_female$WillingRiskySexMean,na.rm=TRUE),2),sep = ","))

### Males
print(paste(length(na.omit(thedata_male$WillingRiskySexMean)),round(mean(thedata_male$WillingRiskySexMean,na.rm=TRUE),2),
             round(sd(thedata_male$WillingRiskySexMean,na.rm=TRUE),3),round(median(thedata_male$WillingRiskySexMean,na.rm=TRUE),2),
             round(min(thedata_male$WillingRiskySexMean,na.rm=TRUE),2),round(max(thedata_male$WillingRiskySexMean,na.rm=TRUE),2),sep = ","))


## Intention to engage in risky sex
print(paste(length(na.omit(thedata$IntentionRiskSexTotal)),round(mean(thedata$IntentionRiskSexTotal,na.rm=TRUE),2),
             round(sd(thedata$IntentionRiskSexTotal,na.rm=TRUE),3),round(median(thedata$IntentionRiskSexTotal,na.rm=TRUE),2),
             round(min(thedata$IntentionRiskSexTotal,na.rm=TRUE),2),round(max(thedata$IntentionRiskSexTotal,na.rm=TRUE),2),sep = ","))

### Females
print(paste(length(na.omit(thedata_female$IntentionRiskSexTotal)),round(mean(thedata_female$IntentionRiskSexTotal,na.rm=TRUE),2),
             round(sd(thedata_female$IntentionRiskSexTotal,na.rm=TRUE),3),round(median(thedata_female$IntentionRiskSexTotal,na.rm=TRUE),2),
             round(min(thedata_female$IntentionRiskSexTotal,na.rm=TRUE),2),round(max(thedata_female$IntentionRiskSexTotal,na.rm=TRUE),2),sep = ","))

### Males
print(paste(length(na.omit(thedata_male$IntentionRiskSexTotal)),round(mean(thedata_male$IntentionRiskSexTotal,na.rm=TRUE),2),
             round(sd(thedata_male$IntentionRiskSexTotal,na.rm=TRUE),3),round(median(thedata_male$IntentionRiskSexTotal,na.rm=TRUE),2),
             round(min(thedata_male$IntentionRiskSexTotal,na.rm=TRUE),2),round(max(thedata_male$IntentionRiskSexTotal,na.rm=TRUE),2),sep = ","))

```

Linear Regression Analysis
```{r, message=FALSE, warning=FALSE, include=FALSE}

# Question 1:
# Does Gender, Ethnicity, and/or Pubertal Status at Grade 8 relate to the likelihood of
# being in situations where sexual risk behavior could occur?
# IVs:  a) Gender
#       b) Ethnicity (identify as Latino)
#       c) Pubertal Status at Grade 8
# DVs:  a) Opportunities monitoring score in Grade 9
#       b) Having an older partner in Grade 9
#       c) EMA time unsupervised w/ partner in Grade 9 + summer
options(scipen=999) 

# Does gender relate to opportunities monitoring score?
gender_oppmon<-lm(OppMonitorMean ~ Gender, data=thedata, na.action=na.omit)
anova(gender_oppmon)  # yes
summary(gender_oppmon) # Males less likely to have opportunities to be unmonitored.
print(paste0("Adj R Square = ",round(summary(gender_oppmon)$adj.r.squared,3),
      " p-value = ",round(anova(gender_oppmon)$'Pr(>F)'[1],4)))

# Does gender relate to the age of one's oldest romantic partner in grade 9?
gender_ageoldpartner<-lm(oldest ~ Gender, data=thedata, na.action=na.omit)
anova(gender_ageoldpartner) # yes
summary(gender_ageoldpartner) # Males less like to have dated older partner
print(paste0("Adj R Square = ",round(summary(gender_ageoldpartner)$adj.r.squared,3),
      " p-value = ",round(anova(gender_ageoldpartner)$'Pr(>F)'[1],5)))

# Does gender relate to EMA time unsupervised w/ partner in grade 9 + summer
gender_ema<-lm(EMAaloneBFGF ~ Gender, data=thedata, na.action=na.omit)
anova(gender_ema) # no
summary(gender_ema)

# Does ethnicity relate to opportunities monitoring score?
ethnicity_oppmon<-lm(OppMonitorMean ~ Ethnicity, data=thedata, na.action=na.omit)
anova(ethnicity_oppmon) # no
summary(ethnicity_oppmon)

# Does ethnicity relate to the age of one's oldest romantic partner in grade 9?
ethnicity_ageoldpartner<-lm(oldest ~ Ethnicity, data=thedata, na.action=na.omit)
anova(ethnicity_ageoldpartner) # yes
summary(ethnicity_ageoldpartner)
print(paste0("Adj R Square = ",round(summary(ethnicity_ageoldpartner)$adj.r.squared,3),
      " p-value = ",round(anova(ethnicity_ageoldpartner)$'Pr(>F)'[1],5)))


# Does ethnicity relate to EMA time unsupervised w/ partner in grade 9 + summer
ethnicity_ema<-lm(EMAaloneBFGF ~ Ethnicity, data=thedata, na.action=na.omit)
anova(ethnicity_ema) # no
summary(ethnicity_ema)

# Does gender and ethnicity interact in relation to to the age of one's oldest romantic partner in grade 9?
gender_ethnicity_ageoldpartner<-lm(oldest ~ Gender* Ethnicity, data=thedata, na.action=na.omit)
anova(gender_ethnicity_ageoldpartner) # yes
summary(gender_ethnicity_ageoldpartner)

gender_ethnicity_ageoldpartner_graph<-ggplot(thedata %>% filter(!is.na(Ethnicity)) %>% filter(!is.na(oldest)),
                                             aes(x=as.factor(Gender), fill=as.factor(oldest))) +
  geom_bar() +
  facet_grid(.~as.factor(Ethnicity),
             scales='free',
              labeller=as_labeller(latino_labels))+
  labs(x="Gender",fill="Oldest romantic partner") + 
  scale_fill_discrete(labels=c("0" = "At least a year younger", "1" = "About same age", "2" = "At least a year older", "3" = "18 years or older")) +
  scale_x_discrete(labels=c("0" = "Female", "1" = "Male"))+
  theme_kate() + theme(legend.position="right")
gender_ethnicity_ageoldpartner_graph


# Does pubertal status at grade 8 relate to opportunities monitoring score?
puberty_oppmon<-lm(OppMonitorMean ~ Puberty_3group, data=thedata, na.action=na.omit)
anova(puberty_oppmon) # no

# What about just the females when divided into late vs. early/typical pubertal timing?
puberty_oppmon<-lm(OppMonitorMean ~ Puberty_2group, data=thedata %>% filter(Gender=="Female"), na.action=na.omit)
anova(puberty_oppmon) # no

# Does pubertal status at grade 8 interact with gender interact in relation to opportunities monitoring score?
gender_puberty_oppmon<-lm(OppMonitorMean ~ Gender * Puberty_3group, data=thedata, na.action=na.omit)
anova(gender_puberty_oppmon) # No

# Does pubertal status at grade 8 relate to the age of one's oldest romantic partner in grade 9?
puberty_ageoldpartner<-lm(oldest ~ Puberty_2group, data=thedata, na.action=na.omit)
anova(puberty_ageoldpartner) # yes
summary(puberty_ageoldpartner)
print(paste0("Adj R Square = ",round(summary(puberty_ageoldpartner)$adj.r.squared,3),
      " p-value = ",round(anova(puberty_ageoldpartner)$'Pr(>F)'[1],5)))

# Does pubertal status at grade 8 relate to EMA time unsupervised w/ partner in grade 9 + summer
puberty_ema<-lm(EMAaloneBFGF ~ Puberty_2group, data=thedata, na.action=na.omit)
anova(puberty_ema) # No

# Does pubertal status at grade 8 interact with ethnicity and gender to 
# relate to the age of one's oldest romantic partner in grade 9?
puberty_gender_ethnicity_ageoldpartner<-lm(oldest ~ Puberty_2group*Gender*Ethnicity, data=thedata, na.action=na.omit)
anova(puberty_gender_ethnicity_ageoldpartner) # no
summary(puberty_gender_ethnicity_ageoldpartner)

# How do our measures of opportunties to have risky sexual behavior correlate?
oppmon_EMAaloneBFGF<-lm(EMAaloneBFGF ~ OppMonitorMean, data=thedata, na.action=na.omit)
anova(oppmon_EMAaloneBFGF) # yes
summary(oppmon_EMAaloneBFGF)
print(paste0("Adj R Square = ",round(summary(oppmon_EMAaloneBFGF)$adj.r.squared,3),
      " p-value = ",round(anova(oppmon_EMAaloneBFGF)$'Pr(>F)'[1],15)))


ageoldpartner_oppmon<-lm(OppMonitorMean ~ oldest, data=thedata, na.action=na.omit)
anova(ageoldpartner_oppmon) # yes
summary(ageoldpartner_oppmon)
print(paste0("Adj R Square = ",round(summary(ageoldpartner_oppmon)$adj.r.squared,3),
      " p-value = ",round(anova(ageoldpartner_oppmon)$'Pr(>F)'[1],5)))

ageoldpartner_EMAaloneBFGF<-lm(EMAaloneBFGF ~ oldest, data=thedata, na.action=na.omit)
anova(ageoldpartner_EMAaloneBFGF) #yes but p = .04 so questionable.
summary(ageoldpartner_EMAaloneBFGF)
print(paste0("Adj R Square = ",round(summary(ageoldpartner_EMAaloneBFGF)$adj.r.squared,3),
      " p-value = ",round(anova(ageoldpartner_EMAaloneBFGF)$'Pr(>F)'[1],5)))


###########################################
# Question 2:
# What predicts conflict in dating behavior?
# IVs:  a) Gender
#       b) Ethnicity
#       c) Pubertal Status at Grade 8
#       d) EMA time unsupervised w/ partner at Grade 9 + summer
#       e) Opportunities monitoring score at Grade 9
#       f) Age of BF/GF Grade 10
# DVs:  a) Conflict dating behavior Grade 10

# Does gender relate to conflict dating behavior Grade 10?
gender_conflict<-lm(DatingConflictMean ~ Gender, data=thedata, na.action=na.omit)
anova(gender_conflict) # No

# Does ethnicity relate to conflict dating behavior Grade 10?
ethnicity_conflict<-lm(DatingConflictMean ~ Ethnicity, data=thedata, na.action=na.omit)
anova(ethnicity_conflict) # No

# Does pubertal status at grade 8 relate to conflict dating behavior Grade 10?
puberty_conflict<-lm(DatingConflictMean ~ Puberty_2group, data=thedata, na.action=na.omit)
anova(puberty_conflict) # No

# What about girls only?
puberty_conflict<-lm(DatingConflictMean ~ Puberty_2group, data=thedata %>% filter(Gender=="Female"), na.action=na.omit)
anova(puberty_conflict) # No

# Does having had an older romantic partner by grade 9 relate to conflict dating behavior Grade 10?
oldest_conflict<-lm(DatingConflictMean ~ oldest, data=thedata, na.action=na.omit)
anova(oldest_conflict) # No

# Is there an interaction wtih gender?
oldest_gender_conflict<-lm(DatingConflictMean ~ oldest*Gender, data=thedata, na.action=na.omit)
anova(oldest_gender_conflict) # No
# Is there an interaction wtih ethnicity?
oldest_ethnicity_conflict<-lm(DatingConflictMean ~ oldest*Ethnicity, data=thedata, na.action=na.omit)
anova(oldest_ethnicity_conflict) # No
# Is there an interaction wtih puberty?
oldest_puberty_conflict<-lm(DatingConflictMean ~ oldest*Puberty_2group, data=thedata, na.action=na.omit)
anova(oldest_puberty_conflict) # No

# Does having opportunties to engage in risky sexual activity relate to conflict dating behavior Grade 10?
oppmon_conflict<-lm(DatingConflictMean ~ OppMonitorMean, data=thedata, na.action=na.omit)
anova(oppmon_conflict) # yes
summary(oppmon_conflict) 
print(paste0("Adj R Square = ",round(summary(oppmon_conflict)$adj.r.squared,3),
      " p-value = ",round(anova(oppmon_conflict)$'Pr(>F)'[1],9)))

# Is there an interaction wtih gender?
oppmon_gender_conflict<-lm(DatingConflictMean ~ OppMonitorMean*Gender, data=thedata, na.action=na.omit)
anova(oppmon_gender_conflict) # Yes
print(paste0("Adj R Square = ",round(summary(oppmon_gender_conflict)$adj.r.squared,3),
      " p-value = ",round(anova(oppmon_gender_conflict)$'Pr(>F)'[1],9)))


oppmon_gender_conflict_graph<-ggplot(thedata %>% filter(!is.na(DatingConflictMean)),
                                             aes(x=OppMonitorMean, y=DatingConflictMean, 
                                                 colour=Gender)) +
geom_point(aes(colour=Gender),alpha=.3)+
  geom_smooth(method=lm,
                aes(x=OppMonitorMean, y=DatingConflictMean, colour=Gender),
                size=.7,
                alpha=0.2)+
  labs(x="Opportunity Monitor Mean Score",
       y="CADRI mean score",colour="Gender")+
  theme_kate() + theme(legend.position="right")
oppmon_gender_conflict_graph

# Is there an interaction wtih ethnicity?
oppmon_ethnicity_conflict<-lm(DatingConflictMean ~ OppMonitorMean*Ethnicity, data=thedata, na.action=na.omit)
anova(oppmon_ethnicity_conflict) # Yes
print(paste0("Adj R Square = ",round(summary(oppmon_ethnicity_conflict)$adj.r.squared,3),
      " p-value = ",round(anova(oppmon_ethnicity_conflict)$'Pr(>F)'[1],9)))


oppmon_ethnicity_conflict_graph<-ggplot(thedata %>% filter(!is.na(DatingConflictMean)) %>% filter(!is.na(Ethnicity)),
                                             aes(x=OppMonitorMean, y=DatingConflictMean, 
                                                 colour=as.factor(Ethnicity))) +
geom_point(aes(colour=as.factor(Ethnicity)),alpha=.3)+
  geom_smooth(method=lm,
                aes(x=OppMonitorMean, y=DatingConflictMean, colour=as.factor(Ethnicity)),
                size=.7,
                alpha=0.2)+
  labs(x="Opportunity Monitor Mean Score",
       y="CADRI mean score",colour="Ethnicity")+
  scale_colour_discrete(labels=latino_labels)+
  theme_kate() + theme(legend.position="right")
oppmon_ethnicity_conflict_graph

# Is there an interaction wtih puberty?
oppmon_puberty_conflict<-lm(DatingConflictMean ~ OppMonitorMean*Puberty_2group, data=thedata, na.action=na.omit)
anova(oppmon_puberty_conflict) # No

# Is there a three way interaction with Gender and Ethnicity?
oppmon_gender_ethnicity_conflict<-lm(DatingConflictMean ~ OppMonitorMean*Gender*Ethnicity, data=thedata, na.action=na.omit)
anova(oppmon_gender_ethnicity_conflict) # No

# Does having opportunties to engage in risky sexual activity (EMA) relate to conflict dating behavior Grade 10?
ema_conflict<-lm(DatingConflictMean ~ EMAaloneBFGF, data=thedata, na.action=na.omit)
anova(ema_conflict) #no

# Is there an interaction with gender?
ema_gender_conflict<-lm(DatingConflictMean ~ EMAaloneBFGF*Gender, data=thedata, na.action=na.omit)
anova(ema_gender_conflict) #no
# Is there an interaction with ethnicity?
ema_ethnic_conflict<-lm(DatingConflictMean ~ EMAaloneBFGF*Ethnicity, data=thedata, na.action=na.omit)
anova(ema_ethnic_conflict) #no
# Is there an interaction with puberty?
ema_puberty_conflict<-lm(DatingConflictMean ~ EMAaloneBFGF*Puberty_2group, data=thedata, na.action=na.omit)
anova(ema_puberty_conflict) #no

# Do our measures of opportunities to engage in risky sexual activity interact to relate to conflict dating behavior Grade 10?
oppmon_ema_conflict<-lm(DatingConflictMean ~ OppMonitorMean*EMAaloneBFGF, data=thedata, na.action=na.omit)
anova(oppmon_ema_conflict) # no
summary(oppmon_ema_conflict)



###########################################
# Question 3:
# What predicts willingness to engage in risky sex?
# IVs:  a) Gender
#       b) Ethnicity
#       c) Pubertal Status at Grade 8
#       d) EMA time unsupervised w/ partner at Grade 9 + summer
#       e) Opportunities monitoring score at Grade 9
#       f) Age of BF/GF Grade 10
# DVs:  a) Willingness to engage in risky sex Grade 10

# Does gender relate to willingness to engage in risky sex Grade 10?
gender_willing<-lm(WillingRiskySexMean ~ Gender, data=thedata, na.action=na.omit)
anova(gender_willing) # Yes
summary(gender_willing) # Males more willing
print(paste0("Adj R Square = ",round(summary(gender_willing)$adj.r.squared,3),
      " p-value = ",round(anova(gender_willing)$'Pr(>F)'[1],9)))

# Does ethnicity relate to willingness to engage in risky sex Grade 10?
ethnicity_willing<-lm(WillingRiskySexMean ~ Ethnicity, data=thedata, na.action=na.omit)
anova(ethnicity_willing) # Yes
summary(ethnicity_willing) # Latinos more willing
print(paste0("Adj R Square = ",round(summary(ethnicity_willing)$adj.r.squared,3),
      " p-value = ",round(anova(ethnicity_willing)$'Pr(>F)'[1],9)))

# Does pubertal status at grade 8 relate to willingness to engage in risky sex Grade 10?
puberty_willing<-lm(WillingRiskySexMean ~ Puberty_2group, data=thedata, na.action=na.omit)
anova(puberty_willing) # No

# Does having had an older romantic partner by grade 9 relate to willingness to engage in risky sex Grade 10?
oldest_willing<-lm(WillingRiskySexMean ~ oldest, data=thedata, na.action=na.omit)
anova(oldest_willing) # No

# Is there an interaction wtih gender?
oldest_gender_willing<-lm(WillingRiskySexMean ~ oldest*Gender, data=thedata, na.action=na.omit)
anova(oldest_gender_willing) # No
# Is there an interaction wtih ethnicity?
oldest_ethnicity_willing<-lm(WillingRiskySexMean ~ oldest*Ethnicity, data=thedata, na.action=na.omit)
anova(oldest_ethnicity_willing) # No
# Is there an interaction wtih puberty?
oldest_puberty_willing<-lm(WillingRiskySexMean ~ oldest*Puberty_2group, data=thedata, na.action=na.omit)
anova(oldest_puberty_willing) # No

# Does having opportunties to engage in risky sexual activity relate to willingness to engage in risky sex Grade 10?
oppmon_willing<-lm(WillingRiskySexMean ~ OppMonitorMean, data=thedata, na.action=na.omit)
anova(oppmon_willing) # yes
summary(oppmon_willing) 
print(paste0("Adj R Square = ",round(summary(oppmon_willing)$adj.r.squared,3),
      " p-value = ",round(anova(oppmon_willing)$'Pr(>F)'[1],9)))

# Is there an interaction wtih gender?
oppmon_gender_willing<-lm(WillingRiskySexMean ~ OppMonitorMean*Gender, data=thedata, na.action=na.omit)
anova(oppmon_gender_willing) # Yes
print(paste0("Adj R Square = ",round(summary(oppmon_gender_willing)$adj.r.squared,3),
      " p-value = ",round(anova(oppmon_gender_willing)$'Pr(>F)'[1],9)))

oppmon_gender_willing_graph<-ggplot(thedata %>% filter(!is.na(WillingRiskySexMean)),
                                             aes(x=OppMonitorMean, y=WillingRiskySexMean, 
                                                 colour=Gender)) +
geom_point(aes(colour=Gender),alpha=.3)+
  geom_smooth(method=lm,
                aes(x=OppMonitorMean, y=WillingRiskySexMean, colour=Gender),
                size=.7,
                alpha=0.2)+
  labs(x="Opportunity Monitor Mean Score",
       y="Willingness to engage in risky sex",colour="Gender")+
  theme_kate() + theme(legend.position="right")
oppmon_gender_willing_graph

# Is there an interaction wtih ethnicity?
oppmon_ethnicity_willing<-lm(WillingRiskySexMean ~ OppMonitorMean*Ethnicity, data=thedata, na.action=na.omit)
anova(oppmon_ethnicity_willing) # No

# Is there an interaction wtih puberty?
oppmon_puberty_willing<-lm(WillingRiskySexMean ~ OppMonitorMean*Puberty_2group, data=thedata, na.action=na.omit)
anova(oppmon_puberty_willing) # No

# Does having opportunties to engage in risky sexual activity (EMA) relate to willingness to engage in risky sex Grade 10?
ema_willing<-lm(WillingRiskySexMean ~ EMAaloneBFGF, data=thedata, na.action=na.omit)
anova(ema_willing) # Yes
print(paste0("Adj R Square = ",round(summary(ema_willing)$adj.r.squared,3),
      " p-value = ",round(anova(ema_willing)$'Pr(>F)'[1],9)))


# Is there an interaction with gender?
ema_gender_willing<-lm(WillingRiskySexMean ~ EMAaloneBFGF*Gender, data=thedata, na.action=na.omit)
anova(ema_gender_willing) #no
# Is there an interaction with ethnicity?
ema_ethnic_willing<-lm(WillingRiskySexMean ~ EMAaloneBFGF*Ethnicity, data=thedata, na.action=na.omit)
anova(ema_ethnic_willing) #no
# Is there an interaction with puberty?
ema_puberty_willing<-lm(WillingRiskySexMean ~ EMAaloneBFGF*Puberty_2group, data=thedata, na.action=na.omit)
anova(ema_puberty_willing) #no

# Do our measures of opportunities to engage in risky sexual activity interact to relate to willingness to engage in risky sex Grade 10?
oppmon_ema_willing<-lm(WillingRiskySexMean ~ OppMonitorMean*EMAaloneBFGF, data=thedata, na.action=na.omit)
anova(oppmon_ema_willing) # no
summary(oppmon_ema_willing)



###########################################
# Question 4:
# What predicts intention to engage in risky sex?
# IVs:  a) Gender
#       b) Ethnicity
#       c) Pubertal Status at Grade 8
#       d) EMA time unsupervised w/ partner at Grade 9 + summer
#       e) Opportunities monitoring score at Grade 9
#       f) Age of BF/GF Grade 10
# DVs:  a) Intention to engage in risky sex Grade 10

# Does gender relate to willingness to engage in risky sex Grade 10?
gender_intention<-lm(IntentionRiskSexTotal ~ Gender, data=thedata, na.action=na.omit)
anova(gender_intention) # Yes
summary(gender_intention) # Males more intention
print(paste0("Adj R Square = ",round(summary(gender_intention)$adj.r.squared,3),
      " p-value = ",round(anova(gender_intention)$'Pr(>F)'[1],9)))

# Does ethnicity relate to intentionness to engage in risky sex Grade 10?
ethnicity_intention<-lm(IntentionRiskSexTotal ~ Ethnicity, data=thedata, na.action=na.omit)
anova(ethnicity_intention) # No

# Does pubertal status at grade 8 relate to intentionness to engage in risky sex Grade 10?
puberty_intention<-lm(IntentionRiskSexTotal ~ Puberty_2group, data=thedata, na.action=na.omit)
anova(puberty_intention) # No

# Does having had an older romantic partner by grade 9 relate to intentionness to engage in risky sex Grade 10?
oldest_intention<-lm(IntentionRiskSexTotal ~ oldest, data=thedata, na.action=na.omit)
anova(oldest_intention) # No

# Is there an interaction wtih gender?
oldest_gender_intention<-lm(IntentionRiskSexTotal ~ oldest*Gender, data=thedata, na.action=na.omit)
anova(oldest_gender_intention) # No
# Is there an interaction wtih ethnicity?
oldest_ethnicity_intention<-lm(IntentionRiskSexTotal ~ oldest*Ethnicity, data=thedata, na.action=na.omit)
anova(oldest_ethnicity_intention) # Yes but not model significant
print(paste0("Adj R Square = ",round(summary(oldest_ethnicity_intention)$adj.r.squared,3),
      " p-value = ",round(anova(oldest_ethnicity_intention)$'Pr(>F)'[1],9)))

# Is there an interaction with puberty?
oldest_puberty_intention<-lm(IntentionRiskSexTotal ~ oldest*Puberty_2group, data=thedata, na.action=na.omit)
anova(oldest_puberty_intention) # No

# Does having opportunties to engage in risky sexual activity relate to intentionness to engage in risky sex Grade 10?
oppmon_intention<-lm(IntentionRiskSexTotal ~ OppMonitorMean, data=thedata, na.action=na.omit)
anova(oppmon_intention) # yes
summary(oppmon_intention) 
print(paste0("Adj R Square = ",round(summary(oppmon_intention)$adj.r.squared,3),
      " p-value = ",round(anova(oppmon_intention)$'Pr(>F)'[1],9)))

# Is there an interaction wtih gender?
oppmon_gender_intention<-lm(IntentionRiskSexTotal ~ OppMonitorMean*Gender, data=thedata, na.action=na.omit)
anova(oppmon_gender_intention) # No
print(paste0("Adj R Square = ",round(summary(oppmon_gender_intention)$adj.r.squared,3),
      " p-value = ",round(anova(oppmon_gender_intention)$'Pr(>F)'[1],9)))

# Is there an interaction wtih ethnicity?
oppmon_ethnicity_intention<-lm(IntentionRiskSexTotal ~ OppMonitorMean*Ethnicity, data=thedata, na.action=na.omit)
anova(oppmon_ethnicity_intention) # No

# Is there an interaction wtih puberty?
oppmon_puberty_intention<-lm(IntentionRiskSexTotal ~ OppMonitorMean*Puberty_2group, data=thedata, na.action=na.omit)
anova(oppmon_puberty_intention) # No

# Does having opportunties to engage in risky sexual activity (EMA) relate to intentionness to engage in risky sex Grade 10?
ema_intention<-lm(IntentionRiskSexTotal ~ EMAaloneBFGF, data=thedata, na.action=na.omit)
anova(ema_intention) # Yes
print(paste0("Adj R Square = ",round(summary(ema_intention)$adj.r.squared,3),
      " p-value = ",round(anova(ema_intention)$'Pr(>F)'[1],9)))


# Is there an interaction with gender?
ema_gender_intention<-lm(IntentionRiskSexTotal ~ EMAaloneBFGF*Gender, data=thedata, na.action=na.omit)
anova(ema_gender_intention) #no
# Is there an interaction with ethnicity?
ema_ethnic_intention<-lm(IntentionRiskSexTotal ~ EMAaloneBFGF*Ethnicity, data=thedata, na.action=na.omit)
anova(ema_ethnic_intention) #no
# Is there an interaction with puberty?
ema_puberty_intention<-lm(IntentionRiskSexTotal ~ EMAaloneBFGF*Puberty_2group, data=thedata, na.action=na.omit)
anova(ema_puberty_intention) #no

# Do our measures of opportunities to engage in risky sexual activity interact to relate to intentionness to engage in risky sex Grade 10?
oppmon_ema_intention<-lm(IntentionRiskSexTotal ~ OppMonitorMean*EMAaloneBFGF, data=thedata, na.action=na.omit)
anova(oppmon_ema_intention) # no
summary(oppmon_ema_intention)


```

Path Analysis
```{r, message=FALSE, warning=FALSE, include=FALSE}

# Dummy code a few variables
dummydata<-thedata %>%
  mutate(Gender=ifelse(Gender=="Female",0,
                       ifelse(Gender=="Male",1,NA))) %>%
  mutate(Puberty_2group=ifelse(Puberty_2group=="less",0,
                               ifelse(Puberty_2group=="avg",1,NA))) %>%
  mutate(Ethnicity=as.numeric(as.character(Ethnicity))) %>%
           select(-Puberty_3group)


# Create the correlation matrix
corrmatrix<-cor(dummydata,use = "pairwise.complete.obs")
rownames(corrmatrix)<-colnames(corrmatrix)<-colnames(dummydata)



# Model 1: Original conceptual model
# Specify the model
DatingConflictModel<-'
OppMonitorMean~Gender+Puberty_2group+Ethnicity
oldest~Gender+Puberty_2group+Ethnicity
EMAaloneBFGF~Gender+Puberty_2group+Ethnicity
DatingConflictMean~Gender
DatingConflictMean~Puberty_2group
DatingConflictMean~Ethnicity
DatingConflictMean~OppMonitorMean
DatingConflictMean~oldest
DatingConflictMean~EMAaloneBFGF
'
# Estimate the model
results<-sem(DatingConflictModel,sample.cov=corrmatrix,sample.nobs=394)

# Display results
summary(results,standardized=T,fit.measures=T,rsq=T)

# Plot results
output<-semPaths(results,'std',layout='tree')

# Create labels
lbls<-c("Opportunities\nMonitoring",
        "Oldest\nPartner",
        "EMA Alone\nw/ Partner",
        "CADRI\nScore",
        "Gender","Puberty","Latino")

# Define the groups
grps<-list(covariates=c("Gender","Puberty_2group","Ethnicity"),
           riskfactors=c("OppMonitorMean","oldest","EMAaloneBFGF"),
           outcome=c("DatingConflictMean"))

#new plot
semPaths(results,what="std",
                  layout="tree",
                  residuals=FALSE,
                  nCharNodes=0,
                  groups=grps,
                  color=c("dodgerblue","violetred3","chartreuse4"),
                  posCol=c("blue","red"),
                  nodeLabels=lbls,
                  sizeMan=8,
                  edge.label.cex=1.0,
                  legend=FALSE,
                  filetype="png",
                  filename="../graphs/SEM_model1",
                  height = 5, width = 10)


# Model 2: Remove "oldest" from the model
# Specify the model
DatingConflictModel2<-'
OppMonitorMean~Gender+Puberty_2group+Ethnicity
EMAaloneBFGF~Gender+Puberty_2group+Ethnicity
DatingConflictMean~Gender
DatingConflictMean~Puberty_2group
DatingConflictMean~Ethnicity
DatingConflictMean~OppMonitorMean
DatingConflictMean~EMAaloneBFGF
'
# Estimate the model
results2<-sem(DatingConflictModel2,sample.cov=corrmatrix,sample.nobs=394)

# Display results
summary(results2,standardized=T,fit.measures=T,rsq=T)

# Plot results
output2<-semPaths(results2,'std',layout='tree')

# Create labels
lbls2<-c("Opportunities\nMonitoring",
        "EMA Alone\nw/ Partner",
        "CADRI\nScore",
        "Gender","Puberty","Latino")

# Define the groups
grps2<-list(covariates=c("Gender","Puberty_2group","Ethnicity"),
           riskfactors=c("OppMonitorMean","EMAaloneBFGF"),
           outcome=c("DatingConflictMean"))

#new plot
semPaths(results2,what="std",
                  layout="tree",
                  residuals=FALSE,
                  nCharNodes=0,
                  groups=grps2,
                  color=c("dodgerblue","violetred3","chartreuse4"),
                  posCol=c("blue","red"),
                  nodeLabels=lbls2,
                  sizeMan=8,
                  edge.label.cex=1.0,
                  legend=FALSE,
                  filetype="png",
                  filename="../graphs/SEM_model2",
                  height = 5, width = 10)

# Model 3: Kate trying to figure out a parsimonious model that is a good fit
# Specify the model
DatingConflictModel3<-'
OppMonitorMean~Gender+Puberty_2group+Ethnicity
DatingConflictMean~Gender+Ethnicity+OppMonitorMean
'
# Estimate the model
results3<-sem(DatingConflictModel3,sample.cov=corrmatrix,sample.nobs=394)

# Display results
summary(results3,standardized=T,fit.measures=T,rsq=T)

# Create labels
lbls3<-c("Opportunities\nMonitoring",
        "CADRI\nScore",
        "Gender","Puberty","Latino")

# Define the groups
grps3<-list(covariates=c("Gender","Puberty_2group","Ethnicity"),
           riskfactors=c("OppMonitorMean"),
           outcome=c("DatingConflictMean"))

#new plot
semPaths(results3,what="std",
                  layout="tree",
                  residuals=FALSE,
                  nCharNodes=0,
                  groups=grps3,
                  color=c("dodgerblue","violetred3","chartreuse4"),
                  posCol=c("blue","red"),
                  nodeLabels=lbls3,
                  sizeMan=8,
                  edge.label.cex=1.0,
                  legend=FALSE,
                  filetype="png",
                  filename="../graphs/SEM_model3",
                  height = 5, width = 10)



```

Multivariate Multiple Linear Regression Analysis & Multiple Regression Analysis
```{r, message=FALSE, warning=FALSE, include=FALSE}

## Multivariate Multiple Regression
model.1 <- manova(cbind(OppMonitorMean,oldest,EMAaloneBFGF) ~ Gender*Ethnicity*Puberty_2group, data = thedata, na.action=na.omit)
summary.aov(model.1)
heplot(model.1)


model.1 <- lm(cbind(OppMonitorMean,oldest,EMAaloneBFGF) ~ Gender*Ethnicity*Puberty_2group, data = thedata, na.action=na.omit)
Anova(model.1,test.statistic="Roy")
anova(model.1,test="Roy")
heplot(model.1)


## Big ole multiple regression
model.2<-lm(DatingConflictMean~ 
             Gender*
             Ethnicity*
             Puberty_2group*
             OppMonitorMean*
             oldest*
             EMAaloneBFGF, data=thedata, na.action=na.omit)
summary(model.2)
anova(model.2)

# Trying to whittle down the model
model.3<-lm(DatingConflictMean~
              Ethnicity*
              Gender*
              Puberty_2group*
              OppMonitorMean*
              EMAaloneBFGF, data=thedata, na.action=na.omit)
summary(model.3)
anova(model.3)

# Whittling
model.4<-lm(DatingConflictMean ~ 
              Gender*
              Ethnicity*
              Puberty_2group*
              OppMonitorMean, data=thedata, na.action=na.omit)
summary(model.4)
anova(model.4)

```